### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'unicorn

### ISSUE THREAD

**Issue by marckraw** [oclif/eslint-config-oclif#93]
hey hey, after making my annual upgrade of deps, i foung out that error when using

```
ESLint: 8.4.1,
eslint-config-oclif: 4.0.0
```

using node `16.13.1` 

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Failed to load plugin 'unicorn' declared in '@sb-mig/sb-mig/.eslintrc » eslint-config-oclif': Package subpath './lib/rules/no-warning-comments' is not defined by "exports" in /Users/marckraw/Projects/Private/__sb-mig/sb-mig/node_modules/eslint/package.json
Referenced from: /Users/marckraw/Projects/Private/__sb-mig/sb-mig/node_modules/eslint-config-oclif/index.js
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/marckraw/Projects/Private/__sb-mig/sb-mig/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/marckraw/Projects/Private/__sb-mig/sb-mig/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:5:18)
```

Let me know, what else information you will need to take a look at that problem :)

**Comment by marckraw** [comment]
Is it something related to esmodules maybe ?

**Comment by Kritten** [comment]
I get the exact same error with Node version v14.15.4 and Eslint on v.8.6.0

**Comment by felipecrs** [comment]
Also receiving this problem.

**Comment by 0xBC84** [comment]
This was fixed in a later version of unicorn. I had to pin the version:

```
"resolutions": {
  "eslint-plugin-unicorn": "^41.0.0"
},
```

**Comment by mikaelkaron** [comment]
> This was fixed in a later version of unicorn. I had to pin the version in `package.json`:
> 
> ```
> "resolutions": {
>   "eslint-plugin-unicorn": "^41.0.0"
> }
> ```

Same if you are using `npm`:

```
  "overrides": {
    "eslint-plugin-unicorn": "^41.0.0"
  }
```

**Comment by mdonnalley** [comment]
Going to close this since it seems like this has been resolved in eslint-plugin-unicorn
